### ISSUE TITLE
Replaces empty values with the string "null"

### ISSUE THREAD

**Issue by jwarkentin** [kwoodson/ansible-role-yedit#50]
If I have a file like the following, the `password` value will actually be changed to `null`.

This:
```yaml
db:
  host: example.com
  user: test
  password:
```

Becomes:
```yaml
db:
  host: example.com
  password: null
  user: test
```

This happens even when editing totally unrelated values in other parts of the config which should obviously not be happening.
