### ISSUE TITLE
Periods in keys

### ISSUE THREAD

**Issue by tdmalone** [kwoodson/ansible-role-yedit#52]
I've got a YAML file (from Elasticsearch) that comes with periods in its keys:

```yaml
filebeat.inputs:
- enabled: false
  paths:
  - /var/log/*.log
  type: log
```

In trying to write to this key, I'm using:

```yaml
- name: Add log file inputs.
  yedit:
    src: /etc/filebeat/filebeat.yml
    key: filebeat.inputs
    value:
      - type: log
        enabled: true
        paths:
          - /var/log/*.log
          - /var/log/cron
          - /var/log/maillog
          - /var/log/messages
          - /opt/log/20*/*/*/*.log
  notify: restart beats
```

Unfortunately this results in duplicating the `filebeat.inputs` key in the destination file, which means the latter (the original one) overrides my new key:

```yaml
filebeat:
  inputs:
  - enabled: true
    paths:
    - /var/log/*.log
    - /var/log/cron
    - /var/log/maillog
    - /var/log/messages
    - /opt/log/20*/*/*/*.log
    type: log
filebeat.inputs:
- enabled: false
  paths:
  - /var/log/*.log
  type: log
```

To try to get yedit to recognise/replace the original `filebeats.input` key, I've tried specifying the `key` in the following ways:

* `filebeat.inputs` (as above)
* `"filebeat.inputs"` (same result as above)
* `"[filebeat.inputs]"` (idea from [here](https://stackoverflow.com/a/42285949/1982136); no match - no changes made to file)
* `filebeat\.inputs` (no match - no changes made to file)
* `"filebeat\.inputs"` (YAML syntax error)

Do you have any ideas for how I could achieve this?

If it's not easy to match a key with a period in it, alternatively I could look at ways to completely remove that duplicate key, although I think that would be a last resort.
