### ISSUE TITLE
Manipulat lists of dictionaries

### ISSUE THREAD

**Issue by keitalbame** [kwoodson/ansible-role-yedit#55]
I was trying this very useful role( hopefully a future module ;) ) and I'm not able to manipulate a list of dictionaries.

What I need to manipulate is something like:
```
nexus_roles:
  - id: users
    name: users_roles
    description: Role to all users
    privileges:
      - nx-search-read
      - all-repos-read
    roles: []
  - id: devs
    name: devs_roles
    description: Role to all devs
    privileges:
      - nx-search-read
      - nx-repository-view-docker-*-*
      - all-repos-read
    roles: []
```
It would be useful to be able to create, delete or update parts or the full dictionary.
I was trying several variants but did not manage to get this to work.

Was this use case not implemented?

Thanks

**Comment by kwoodson** [comment]
@keitalbame, if you have a specific example then I can assist.  I believe replacing or updating parts of the dictionary does work.

**Comment by kwoodson** [comment]
@keitalbame, quick example of how to modify:

```
# example of modifying an entire dictionary
  - yedit:
      content: "{{ nexus_roles }}"
      key: "[0]"
      value:
        id: foo
        description: test
        name: bar
    register: output
# example of modifying a dictionary entry
  - yedit:
      content: "{{ nexus_roles }}"
      key: "[0].name"
      value: user_roles_updated
    register: output
```
