### ISSUE TITLE
Append to list of dicts in a specific location

### ISSUE THREAD

**Issue by BarbzYHOOL** [kwoodson/ansible-role-yedit#61]
I've been reading the doc and trying all the parameters but I wonder if I can go from this with this module:
```
my_var:
  - name: 'name_1'
    id: 111
  - name: 'name_2'
    id: 112
    programs:
      - program_name: "HTTP"
        port: 80
      - program_name: "HTTPS"
        port: 443
  - name: 'name_3'
    id: 113
```

```
my_var:
  - name: 'name_1'
    id: 111
  - name: 'name_2'
    id: 112
    programs:
      - program_name: "HTTP"
        port: 80
      - program_name: "HTTPS"
        port: 443
      - program_name: "new_program_1"
        port: 111
      - program_name: "new_program_2"
        port: 222
  - name: 'name_3'
    id: 113
```

To this, in one task:

```
my_var:
  - name: 'name_1'
    id: 111
  - name: 'name_2'
    id: 112
    programs:
      - program_name: "HTTP"
        port: 80
      - program_name: "HTTPS"
        port: 443
      - program_name: "new_program_1"
        port: 111
      - program_name: "new_program_2"
        port: 222
  - name: 'name_3'
    id: 113
```

I need it to be exactly ordered like that, so inside item with value `name: 'name_3'`
@kwoodson

**Comment by kwoodson** [comment]
@BarbzYHOOL,

When modifying lists there are a couple of options.  If you know the entire value of what the list should be then you can substitute the entire value of `programs` to the value that you expect.  If you are wanting to modify a list of dictionaries, then it becomes a bit more difficult because you will then be attempting to modify items by searching for them. 

Is this config managed or is this a single run that you want to execute?  This makes a difference whether you can append to the list or manage the entire list's contents.
For instance, this works:
```
  - yedit:
      content: "{{ my_var }}"
      key: "[1].programs"
      value:
      - program_name: "HTTP"
        port: 80
      - program_name: "HTTPS"
        port: 443
      - program_name: "new_program_1"
        port: 111
      - program_name: "new_program_2"
        port: 222
    register: output
```
Another example:
```
  - yedit:
      src: myvar.yml
      key: "my_var.[1].programs"
      value: "{{ item }}"
      update: true
    register: output
    with_items:
    - program_name: "new_program_1"
      port: 111
    - program_name: "new_program_2"
      port: 222
```

**Comment by BarbzYHOOL** [comment]
Basically, I edit another yaml file (in host_vars) then I run a role that depends on that yaml file. It should be idempotent so not add the same thing over and over.

I can't make the first example work.

The second one seems to work but:

1) The yaml file looks like that, with 0 indentation, so it won't work:

```
my_var:
- id: 111
  name: name_1
- id: 112
  name: name_2
  programs:
  - port: 80
    program_name: HTTP
  - port: 443
    program_name: HTTPS
  - port: 111
    program_name: new_program_1
  - port: 222
    program_name: new_program_2
- id: 113
  name: name_3
```

2) I need to select the item with `id: 112` or by name, but it can't be with [0] because the list can change and so it won't be at the [0] slot.

What if I made a dict of dicts of dicts ? dunno if it would be better

3) All the vars have been reordered in the opposite order, maybe alphabetically. That's minor

@kwoodson

**Comment by BarbzYHOOL** [comment]
And what if I change to a dict of dict:

```
my_var:
  111:
    name: 'name_1'
    id: 111
  112:
    name: 'name_2'
    id: 112
    programs:
      - program_name: "HTTP"
        port: 80
      - program_name: "HTTPS"
        port: 443
  113:
    name: 'name_3'
    id: 113
```

Then I can maybe append directly to `my_var.112.programs` or `my_vars[112][programs]`, no??
