### ISSUE TITLE
Better support of comments

### ISSUE THREAD

**Issue by dr4Ke** [kwoodson/ansible-role-yedit#76]
Take this `file.yml`:
```yaml
variables:
  var1: VAR1

#This is another definition
other:
  var2: VAR2
```

Use this task:
```yaml
- name: add variable
  yedit:
    src: file.yml
    key: variables.var3
    value: VAR3
```

You end up with `file.yml`:
```yaml
variables:
  var1: VAR1

#This is another definition
  var3: VAR3
other:
  var2: VAR2
```

It's correct in a functional point of view but ugly. It would be better to have:
```yaml
variables:
  var1: VAR1
  var3: VAR3

#This is another definition
other:
  var2: VAR2
```
