### ISSUE TITLE
key validation failure

### ISSUE THREAD

**Issue by atodorov-storpool** [kwoodson/ansible-role-yedit#84]
Having the following _test.yaml_ file

```yaml
:port: 1234
:host: 127.0.0.1
```

The following task will not update the `:host`, silently.
```yaml
---
- name: update host
  yedit:
    src: 'test.yml'
    state: present
    key: ':host'
    value: '0.0.0.0'
```
