### ISSUE TITLE
issues with dots in keys

### ISSUE THREAD

**Issue by olifur** [kwoodson/ansible-role-yedit#90]
Hi kwoodson,

I have the following problem when my keys contain dots such as in domain names

My target yaml structure I want to write:
```yaml
lab00001:
  hosts:
    mydomainname.example.com
       horst
```

Now using quotes I try to escape the dots in the domain name
```ansible
- hosts: localhost
  gather_facts: no
  roles:
  - kwoodson.yedit
  tasks:
  - name: insert simple key, value
    yedit:
      src: /tmp/xxx.yaml
      key: 
        lab00001
          hosts
            "mydomainname.example.com"
      value: horst
      state: present
```

this does not write anything into the file.

Other combinations of escaping dots in yaml do not work either for me, e.g
```ansible
            "mydomainname\.example\.com"
```

If I leave the dots and quotes, it writes content to the file 

```ansible
- hosts: localhost
  gather_facts: no
  roles:
  - kwoodson.yedit
  tasks:
  - name: insert simple key, value
    yedit:
      src: /tmp/xxx.yaml
      key: 
        lab01
          hosts
            mydomainnameXXX
      value: horst
      state: present
```

Is there a way to use dots in keys (escape) with your module?

Thanks in advance,
Oliver

**Comment by olifur** [comment]
After reviewing the source code I found the solution myself


```yaml
 - name: insert simple key, value
    yedit:
      src: /tmp/xxx.yaml
      key: 
        lab01.hosts
      value: 
        horst:
          'mydomainname.abc.it.de'
```
I close the issue for now.
